---

- hosts: localhost
  tasks:
  - name: mount cifs 
    mount:
      path: /logBakServer
      src: //192.168.5.107/logBakServer 
      fstype: cifs
      opts: "username=logServer,password=PmPh#3025#logS"
      state: mounted
