---
- hosts: "{{ host }}"
  tasks:
    - name: copy zabbix.repo dest host
      copy:
        src: /etc/yum.repos.d/zabbix.repo
        dest: /etc/yum.repos.d/zabbix.repo
 
    - name: copy zabbix.repo.key dest host
      copy:
        src: /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
    
    - name: install zabbix-agent
      yum:
        name: zabbix-agent
        state: installed
        enablerepo: zabbix
 
    - name: change zabbix-agent_config in Server
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server='
        line: 'Server=192.168.3.121,192.168.12.28'
 
    - name: change zabbix-agent_config in ServerActive
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive'
        line: 'ServerActive=192.168.3.121,192.168.12.28'
 
    - name: change zabbix-agent_config in Hostname
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname'
        line: 'Hostname={{ ansible_host }}'
 
    - name: change zabbix-agent_config in HostMetadata
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        regexp: '# HostMetadata='
        line: 'HostMetadata=Linux'
    - name: start or restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
