- name: Create crontabs
  cron:
    name: create logrotate daily
    minute: "58"
    hour: "23"
    user: root
    state: present
    job: "/usr/sbin/logrotate -vf /etc/logrotate.d/logfile"
- name: crontab shell
  cron:
    name: SHELL
    env: yes
    job: /bin/bash
- name: crontab path
  cron:
    name: PATH
    env: yes
    job: /sbin:/bin:/usr/sbin:/usr/bin
- name: crontab mail
  cron:
    name: MAILTO
    env: yes
    job: root
  notify:
    - restart crond
  
