- name: ADD logrotate in /etc/logrotate.d/logfile
  blockinfile:
    path: /etc/logrotate.d/logfile
    marker_begin: "start logrotate"
    marker_end: "end logrotate"
    insertafter: ""
    create: true
    state: present
    block: |
      /var/log/notice
      /var/log/warning
      /var/log/error
      /var/log/crit
      /var/log/alert
      /var/log/emerg_log
      {
      daily
      dateext
      dateformat _%Y_%m_%d
      maxage 90
      rotate 90
      missingok
      ifempty
      olddir /logBakServer/systemlog_allserver/{{ inventory_hostname }}
      createolddir 0755 root root
      notifempty
      create 0600 root root
      sharedscripts
      postrotate
          /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
      endscript
      }
  notify:
    - restart crond
