---
# defaults file for pmph-oracl-automation
#
  oracle_user: oracle
  oracle_user_home: "/home/{{ oracle_user }}"
  oracle_group: oinstall
  hostgroup: "{{ group_names[0] }}"
  configure_cluster: false
  configure_oracle_sudo: true
  grid_user: grid
  grid_user_home: "/home/{{ grid_install_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  grid_install_user: "{% if role_separation %}{{ grid_user }}{% else %}{{ oracle_user }}{% endif %}"
  oracle_profile_name_gi: ".profile_grid"    # .profile that sets up the environment for Grid Infrastructure (Cluster or Single node)
  configure_hugepages: true
  configure_hugepages_by: percentage          # percentage/memory
  percent_hugepages: 50                       # Percentage (0-100) of total RAM to dedicate to hugepages, Configures vm.nr_hugepages
  size_in_gb_hugepages: 1                     # The amount of RAM in GB to dedicate to hugepages
  nr_hugepages_percent: "{{((((percent_hugepages/100) * ansible_memtotal_mb)/2)+2)|round|int }}"
  nr_hugepages_memory: "{{ (((size_in_gb_hugepages*1024)/2)+2)|round|int }}"
  nr_hugepages: "{% if configure_hugepages %}{% if configure_hugepages_by|lower == 'percentage'%}{{ nr_hugepages_percent }}{%elif configure_hugepages_by|lower == 'memory' %}{{ nr_hugepages_memory }}{% endif %}{% else %}0{% endif %}"
  role_separation: True
  oracle_groups:
      - { group: oinstall, gid: 1000 }
      - { group: dba , gid: 1001 }
      - { group: oper , gid: 1002 }
      - { group: asmadmin, gid: 1003 }
      - { group: asmoper, gid: 1004 }
      - { group: asmdba, gid: 1005 }
  oracle_users:
      - { username: oracle, uid: 1000, primgroup: oinstall, othergroups: "dba,asmdba,oper" ,passwd: "$6$maSUxV6JSbiIClZq$.VVZviKMY1uH.XQE4dn7QYTHjuuSc5saAHiMy60c0KCxYpsDsn0BRyYhMz0ToLDCDog6UuwVNaTk0.DBSYPdt1" }
  grid_users: 
      - { username: grid, uid: 1001, primgroup: oinstall, othergroups: "asmadmin,asmdba,asmoper,oper,dba", passwd: "$6$maSUxV6JSbiIClZq$.VVZviKMY1uH.XQE4dn7QYTHjuuSc5saAHiMy60c0KCxYpsDsn0BRyYhMz0ToLDCDog6UuwVNaTk0.DBSYPdt1"}
  oracle_directorys:
      - { dir: /oracle/app/oraInventory, owner: grid ,group: oinstall }
      - { dir: /oracle/app/grid, owner: grid ,group: oinstall }
      - { dir: /oracle/app/oracle, owner: oracle ,group: oinstall }
  oracle_seclimits:
      - { name: 'soft nproc', value: 4096 }
      - { name: 'hard nproc', value: 16384 }
      - { name: 'soft nofile', value: 4096 }
      - { name: 'hard nofile', value: 65536 }
      - { name: 'soft stack', value: 10240 }
      - { name: 'hard stack', value: 32768 }
      - { name: 'soft memlock', value: "{{ ((1.2 * ansible_memtotal_mb)*1024)|round|int }}" }
      - { name: 'hard memlock', value: "{{ ((1.2 * ansible_memtotal_mb)*1024)|round|int }}" }
  oracle_grid_seclimits:
      - { name: 'soft nofile', value: 1024 }
      - { name: 'hard nofile', value: 65536 }
      - { name: 'soft nproc', value: 2048 }
      - { name: 'hard nproc', value: 16384 }
  oracle_dba_seclimits:
      - { name: 'hard nofile', value: 65536 }
      - { name: 'soft nofile', value: 65536 }
  oracle_oinstall_seclimits:
      - { name: 'hard nofile', value: 65536 }
      - { name: 'soft nofile', value: 65536 }
  oracle_sysctl:
      - { name: kernel.shmall, value: 60397977 }
      - { name: kernel.shmmni, value: 4096 }
      - { name: kernel.sem, value: "250 256000 100 1024" }
      - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
      - { name: net.ipv4.ip_forward, value: 0 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
      - { name: kernel.sysrq, value: 0 }
      - { name: kernel.core_uses_pid, value: 1 }
      - { name: net.ipv4.tcp_syncookies, value: 1 }
      - { name: kernel.msgmnb, value: 65536 }
      - { name: kernel.msgmax, value: 65536 }
      - { name: net.core.rmem_default, value: 4194304 }
      - { name: net.core.rmem_max, value: 4194304 }
      - { name: net.core.wmem_default, value: 262144 }
      - { name: net.core.wmem_max, value: 1048576 }
      - { name: fs.file-max, value: 6815744 }
      - { name: fs.aio-max-nr, value: 1048576 }
      - { name: kernel.shmmax, value: 68719476736 }
      - { name: kernel.panic_on_oops, value: 1 }
      - { name: vm.min_free_kbytes, value: 524288 }
  oracle_hugepages:
      - { name: vm.nr_hugepages, value: "{{ nr_hugepages }}" }
  multipath: none                   # dm-multipath (Linux device mapper multipath)
  partition_devices: true
  partition_suffix: "{% if multipath |lower == 'dm-multipath' and ansible_distribution_major_version|int == 6  %}p1{% else %}1{% endif%}"
  oracle_asm_init_dg: crs
  oracle_asm_disk_string: "{% if device_persistence|lower == 'asmlib' %}{% elif device_persistence |lower == 'udev' %}/dev/oracle/{% else %}{% endif %}"
  device_persistence: asmlib
  asmlib_rpm: "{% if ansible_distribution_major_version|int==6%}{{asmlib_rpm_el6}}{%elif ansible_distribution_major_version|int==7 %}{{asmlib_rpm_el7}}{% else %}None{% endif %}"
  asmlibsupport_rpm: "{% if ansible_os_family == 'RedHat' %}{% if ansible_distribution_major_version|int==6%}{{asmlibsupport_rpm_el6}}{%elif ansible_distribution_major_version|int==7 %}{{asmlibsupport_rpm_el7}}{% else %}oracleasm-support{% endif %}{% else %}oracleasm-support{% endif %}"
  asmlibsupport_rpm_el7: "https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracleasm-support-2.1.11-2.el7.x86_64.rpm"
  asmlib_rpm_el7: "http://download.oracle.com/otn_software/asmlib/oracleasmlib-2.0.12-1.el7.x86_64.rpm"
  oracle_asm_packages:
      - "{{ asmlib_rpm }}"
      - "{{ asmlibsupport_rpm }}"
      - kmod-oracleasm
  asmadmin_group: asmadmin
  asmlib_binary: "{% if ansible_distribution_major_version|int == 7 %}oracleasm{% elif ansible_distribution_major_version|int == 6  %}/etc/init.d/oracleasm{% else %}/etc/init.d/oracleasm{% endif%}"
  asm_diskgroups:
    - diskgroup: crs
      properties:
        - {redundancy: normal, ausize: 1}
      attributes:
        - {name: 'compatible.rdbms', value: 11.2.0.4.0}
        - {name: 'compatible.asm', value: 12.1.0.2.0}
      disk:
        - {device: /dev/sdb, asmlabel: CRS1}
        - {device: /dev/sdc, asmlabel: CRS2}
    - diskgroup: data
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: 12.1.0.2.0}
      disk:
        - {device: /dev/sdd, asmlabel: DATA1}
        - {device: /dev/sde, asmlabel: DATA2}
        - {device: /dev/sdf, asmlabel: DATA3}
    - diskgroup: rec
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: 12.1.0.2.0}
      disk:
        - {device: /dev/sdg, asmlabel: REC1}
        - {device: /dev/sdh, asmlabel: REC2}
  oracle_stage: /opt/app
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /opt/app/oraInventory
  oracle_home_gi: "{% if configure_cluster %}{{ oracle_home_gi_cl }}{% else %}{{ oracle_home_gi_so }}{% endif %}"
  oracle_home_gi_so: "{{ oracle_base }}/{{ oracle_install_version_gi }}/grid" # ORACLE_HOME for Grid Infrastructure (Stand Alone)
  #install_from_nfs: false
  install_from_nfs: True
  nfs_server_sw: 
  nfs_server_sw_path: /tmp
  oracle_stage_remote: "{{ oracle_stage }}"
  oracle_install_version_gi: 11.2.0.4
  oracle_base: /opt/app/grid/BASE
  oracle_directories:
          - {name: "{{ oracle_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_rsp_stage }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_inventory_loc}}", owner: "{{ grid_install_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/cfgtoollogs", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/admin", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/audit", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/cfgtoollogs/dbca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/cfgtoollogs/sqlpatch", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
          - {name: "{{ oracle_base }}/cfgtoollogs/netca", owner: "{{ oracle_user }}", group: "{{ oracle_group }}", mode: 775 }
  oracle_sw_image_gi:                          # Files containing the installation media for Grid Infrastructure
       - { filename: linuxx64_11204_grid_home.zip, version: 11.2.0.4, creates: 'xdk/mesg/lsxja.msb' }
       - { filename: linuxamd64_11204_grid_2of2.zip, version: 11.2.0.4, creates: 'grid/install/.oui' }
       - { filename: linuxamd64_11c_grid_1of2.zip, version: 11.2.0.4 }
       - { filename: linuxamd64_11c_grid_2of2.zip, version: 11.2.0.4 }


  install_os_packages: true
  extrarepos_enabled:
  extrarepos_disabled:

  oracle_packages:
      - kmod-oracleasm
      - bind-utils
      - binutils
      - compat-libcap1
      - compat-libstdc++-33
      - cpp
      - device-mapper-multipath
      - elfutils-libelf-devel
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - libaio
      - libaio-devel
      - libgcc
      - libstdc++
      - libstdc++-devel
      - libX11
      - libXau
      - libXext
      - libXi
      - libXp
      - libXt
      - libXtst
      - make
      - nfs-utils
      - openssh-clients
      - parted
      - smartmontools
      - sysstat
      - unixODBC-devel
      - util-linux-ng
      - xdpyinfo
      - xorg-x11-utils
      - xorg-x11-xauth
      - xsetroot
      - xterm
      - zlib-devel
